### ISSUE TITLE
2 questions about specific use cases of RRAP

### ISSUE THREAD

**Issue by paigepayne** [thrash-lab/rrap#2]
Hello,

I have two questions which I hope you can answer:

1. Is it possible to run RRAP with a .fna file of annotated genes (i.e., from DRAM) in place of a reference genome? For example, this is what we tried:
`nohup rrap -i <path_to_metaG_paths.txt>  -rg  <path_to_DRAM_genes.fna> -o <path_to_output_directory> -n name -suffix _DNA_R1.fastq > <path_for_nohup.txt> &`
I have tried using genes.fna with and without spaces in the headers, but what ends up happening is the file allgenomes_cat.fna generated by RRAP omits all header/annotation information and I am left with one RPKM value per metagenome that just says "genes" instead of one RPKM value per annotation.

2. Will this program work with metatranscriptome reads that have already had rRNA subtracted, leading to a different number of R1 vs R2 reads (no longer paired)? I know the command is different in bowtie2 for unpaired reads, so I just wanted to make sure.

Thanks in advance for your help.

**Comment by Kojiconner** [comment]
1. RRAP uses the read alignment tool bowtie2 which supports fna files. Try using the option "--skip-merge-contigs". The option will prevent RRAP from merging contigs within an individual fna file. 

2. Unfortunately, RRAP does not support read alignment of unpaired reads at this time.
